.\" Process this file with
.\" groff -man -Tascii oci-image-cleanup.8
.\"
.\" Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.
.\"

.TH OCI-IMAGE-CLEANUP 1 "03 Apr 2018" Linux "User Manuals"
.SH NAME
oci-image-cleanup \- This script runs a set of cleanup steps to prepare instance for snapshot
.SH SYNOPSIS
/usr/libexec/oci-image-cleanup [-h]
.SH DESCRIPTION
This script runs a set of cleanup steps to prepare OCI OL instances for custom images
WARNING!!! This script will clear ssh keys and root passwd.
Upon execution of this script, if you choose to clear the ssh keys, you will no longer be able to login to this instance with your existing credentials.
You will need to create a new custom image of this instance first and then create a new compute instance from that custom image to login.

.BR oci-image-cleanup(8) 
requires root privileges.

More info on custom images can be found here:

https://docs.us-phoenix-1.oraclecloud.com/Content/Compute/Tasks/managingcustomimages.htm

.SH OPTIONS
.IP -h
print this help message
.SH AUTHOR
Sweekar Pinto (sweekar.pinto@oracle.com)

