#!/bin/sh

# Copyright (c) 2020 Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.



export http_proxy=http://www-proxy-hqdc.us.oracle.com:80
export https_proxy=https://www-proxy-hqdc.us.oracle.com:80

/bin/sudo --preserve-env $*




