#!/bin/sh

# Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at
# http://oss.oracle.com/licenses/upl.

# utility to expand a partition or lvm and the filesystem.

_PY3=/usr/bin/python3
_PY_CMD=oci_growfs_main.py
s_dir=`${_PY3} -c 'import os.path ; import oci_utils.impl ; print (os.path.dirname(oci_utils.impl.__file__))' 2>/dev/null`

exec ${_PY3}  ${s_dir}/${_PY_CMD} "$@"

