#!/bin/bash -x
#
# Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown
# at http://oss.oracle.com/licenses/upl.
#
# creates a volume of 51GB, creates a primary partition of 10GB and creates a filesystem on this partition; a destroy
# script is als created.
#
NBPAR="${#}"
VALIDFS=(ext4 xfs)

Usage() {
  echo "Usage:"
  echo "    ${0} [ext4|xfs] (volume name)"
}
# command line
# file system type
if [ "${NBPAR}" -lt 1 ]; then
  echo "Invalid filesystem type: ext4|xfs."
  Usage
  exit 1
else
  FSTYPE=${1}
  if [[ ! " ${VALIDFS[*]} " =~ ${FSTYPE} ]]; then
    echo "Invalid file system type."
    Usage
  fi
fi
#
# volume name
if [ ${NBPAR} -lt 2 ]; then
  VOLNAME=gtijsken_vol01
else
  VOLNAME="${2}"
fi

echo "${VOLNAME}"
#
oci-iscsi-config create --size 51 --volume-name "${VOLNAME}" --attach-volume
#
oci-iscsi-config show --details --no-truncate
#
VOL=$(oci-iscsi-config show --details --output-mode parsable |grep "${VOLNAME}")
echo "${VOL}"
#
IFS='#'; arrVOL=(${VOL}); unset IFS;
echo "${arrVOL}"
DEVICE="/dev/${arrVOL[6]}"
echo "${DEVICE}"
#
fdisk "${DEVICE}" <<EOFF
n
p
1

+10G
p
w
EOFF
sleep 20 
if [ "${FSTYPE}" == "ext4" ]; then
  mkfs.ext4 "${DEVICE}"1
elif [ "${FSTYPE}" == "xfs" ]; then
  mkfs.xfs "${DEVICE}"1
else
  echo "invalid file system type."
  Usage
  exit 1
fi

MOUNTPOINT="/${arrVOL[6]}1"
mkdir -p "${MOUNTPOINT}"
mount "${DEVICE}"1 "${MOUNTPOINT}"
oci-iscsi-config show --details --no-truncate
df -h
#
#
destroy_script="${HOME}/work/destroy_volume_${VOLNAME}"
echo '#!/bin/bash -x' > "${destroy_script}"
echo "umount ${MOUNTPOINT}" >> "${destroy_script}"
IQN=$(oci-volume-data --key "${VOLNAME}" --par iqn --value-only)
OCID=$(oci-volume-data --key "${VOLNAME}" --par ocid --value-only)
echo "oci-iscsi-config detach -I ${IQN}" >> "${destroy_script}"
echo "oci-iscsi-config destroy -O ${OCID} --yes" >> "${destroy_script}"
echo "df -h" >> "${destroy_script}"
echo "oci-iscsi-config show --details --no-truncate" >> "${destroy_script}"
echo "rmdir ${MOUNTPOINT}" >> "${destroy_script}"
chmod 755 "${destroy_script}"
echo "created ${destroy_script}"
