.\" Process this file with
.\" groff -man -Tascii oci-image-migrate.1
.\"
.\" Copyright (c) 2017, 2019 Oracle and/or its affiliates. All rights reserved.
.\"

.TH OCI-IMAGE-MIGRATE 1 "JUNE 2019" Linux "User Manuals"
.SH NAME
oci-image-migrate \- migrate on premise vm to the Oracle Cloud Infrastructure
.SH SYNOPSIS
.B oci-image-migrate [-i
.I inputimage
.B ] [-b
.I bucketname
.B ] [-o
.I outputimage
.B ] [ --quiet] [--verbose] [--help]


Utility to support preparation of on-premise legacy images for importing in
the Oracle Cloud Infrastructure.

