.\" Process this file with
.\" groff -man -Tascii oci-kvm.1
.\"
.\" Copyright (c) 2017 Oracle and/or its affiliates. All rights reserved.
.\"
.TH OCI-ISCSI-CONFIG 1 "FEBRUARY 2018" Linux "User Manuals"
.SH NAME
oci-kvm \- install and remove KVM guests on OCI instances
.SH SYNOPSIS
.B oci-kvm create -D|--domain
.I NAME
.B [-d|--disk
.I DISK_PATH
.B ] [-n|--net
.I IP
.B ] -V|--virt
.I VIRT-INSTALL_ARGS

.B oci-kvm destroy -D|--domain
.I NAME

.SH DESCRIPTION
The
.B oci-kvm
utility is used to create and configure KVM guests on Oracle Cloud Infrastructure (OCI)
instances that use OCI resources, such as block storage and networking, directly.  It
automates all steps of the guest creation process while also ensuring that OCI resources
have not been assigned to more than one KVM guest.  When a guest has outlived
its usefulness, the utility can also remove and/or unconfigure all system resources
that were assigned to the guest.

The
.B oci-kvm create
subcommand performs all actions required to create a KVM guest that uses OCI Block
Storage and OCI VNICs for the root disk and network interface respectively.  For block
storage, the device itself is validated and checked to ensure it has not been assigned
to another guest.  For virtual network interfaces, all virtual network infrastructure
is created automatically.  This includes virtual functions, VLANs, etc.  Indiviual
block storage devices and VNICs are required for each guest.  Guests cannot share
either a VNIC or a block storage device.

.SH OPTIONS
.IP "-D NAME, --domain NAME"
For both the
.B create
and
.B destroy
subcommands, operate on the given libvirt domain name.
.IP "-d DISK_PATH, --disk DISK_PATH"
The path to the block device that will be the root device for the new guest.  If this
option is not specified, an unused block device will be chosen arbitrarily.
.IP "-n IP, --net IP"
The IP address of the OCI VNIC that should be assigned to the new guest.  If this
option is not specified, an unused VNIC will be chosen arbitrarily.
.IP "-V VIRT-INSTALL_ARGS, --virt VIRT-INSTALL_ARGS"
Each argument that appears after either -V or --virt is passed into virt-install when
this tool executes that command.
.B  oci-kvm
 itself provides the following arguments:
--hvm, --name, --cpu, --disk, --network.
.IP --help

.SH DIAGNOSTICS
Return an exit status of 0 for success or 1 if an error occured.
