.\" Process this file with
.\" groff -man -Tascii oci-kvm.1
.\"
.\" Copyright (c) 2018, 2019 Oracle and/or its affiliates. All rights reserved.
.\"
.TH OCI-KVM 1 "MAY 2018" Linux "User Manuals"
.SH NAME
oci-kvm \- install and remove KVM guests on Oracle Cloud Infrastructure instances
.SH SYNOPSIS
.B oci-kvm create -D|--domain
.I NAME
.B [-d|--disk
.I DISK_PATH
.B ] [-v|--virtual-network
.I NETWORK
.B ] [-n|--net
.I IP
.B ]  [-p|--pool
.I POOL
.B ]  [-s|--disk-size
.I DISK_SIZE
.B ] -V|--virt
.I VIRT-INSTALL_ARGS

.B oci-kvm destroy -D|--domain
.I NAME
.B [--destroy-disks]

.B oci-kvm create-pool  -n|--name
.I NAME
.B {-d
.I DEVICE
.B |-N
.I HOST
.B -p
.I PATH}

.B oci-kvm create-network -n|--net
.I NET
.B -N|--network-name
.I NETWORK_NAME
.B -v|--vcn-cidr
.I VCN_CIDR
.B -F|--ip-first
.I IP_FIRST
.B -E|--ip-end
.I IP_END
.B -S|--ip-start
.I IP_START
.B -P|--ip-prefix
IP_PREFIX

.B oci-kvm delete-network -N|--network-name
.I NETWORK_NAME

.SH DESCRIPTION
The
.B oci-kvm
utility is used to create and configure KVM guests on Oracle Cloud Infrastructure
instances that use Oracle Cloud Infrastructure resources, such as block storage and networking, directly.  It
automates all steps of the guest creation process while also ensuring that Oracle Cloud Infrastructure resources
have not been assigned to more than one KVM guest.  When a guest has outlived
its usefulness, the utility can also remove and/or unconfigure all system resources
that were assigned to the guest.

The
.B oci-kvm create
subcommand performs all actions required to create a KVM guest that uses Oracle Cloud Infrastructure Block
Storage and Oracle Cloud Infrastructure VNICs for the root disk and network interface respectively.  For block
storage, the device itself is validated and checked to ensure it has not been assigned
to another guest. A storage pool can also be used. For virtual network interfaces, all virtual network infrastructure
is created automatically.  This includes virtual functions, VLANs, etc.  Indiviual
block storage devices and VNICs are required for each guest.  Guests cannot share
either a VNIC or a block storage device.

The
.B oci-kvm create-pool
subcommand creates a storage pool to host guest virtual disks. Pools can be created upon local disk, block storage of FSS space.

The
.B oci-kvm create-network
subcommand creates a libvirt network on top of OCI vNIC. The created network offers an IP range usable by other KVM guests.
See the '--virtual-network' option of the
.B create
command

The
.B oci-kvm delete-network
subcommand deletes a libvirt network previously created by
.B create-network
command.

When the oci-utils-kvm is installed, it changes the configuration of
.BR ocid(8)
setting
.BR vf_net = true
in
.BR /etc/oci-utils.conf.d/10-oci-kvm.conf .
This causes
.BR ocid(8)
to stop automatically configuring VNICs and instead leaving them for the kvm
tools to manage.

.SH OPTIONS
.IP "--destroy-disks"
For the destroy command, specify that all disks based on libvirt storage pool must alos be deleted
.IP "-D NAME, --domain NAME"
For both the
.B create
and
.B destroy
subcommands, operate on the given libvirt domain name.
.IP "-d DISK_PATH, --disk DISK_PATH"
For the
.B create
command, the path to the block device that will be the root device for the new guest.  If this
option is not specified, an unused block device will be chosen arbitrarily. This option is exclusive with --pool.
.br
For the
.B create-pool
command, the block device that will be used to build the storage pool.
.IP "-N NETWORK_NAME, --network-name NETWORK_NAME"
For the
.B create-network
and the
.B delete-network
commands, the name of the virtual (libvirt) network
.IP "-n NAME, --name NAME"
For the
.B create-pool
command, the name of the pool. When not specified, the default name is the chosen disk name
.IP "-n IP, --net IP"
For the
.B create
command, on bare metal instance host, the IP address of the Oracle Cloud Infrastructure VNIC that should be assigned to the new guest.
On virtual machine instance host the name of the Oracle Cloud Infrastructure VNIC. If this
option is not specified, an unused VNIC will be chosen arbitrarily.
For the
.B create-network
command, the IP address of the Oracle Cloud Infrastructure VNIC that should be used to build the network
.IP "-v VIRTUAL_NETWORK, --virtual-network VIRTUAL_NETWORK"
The name of the libvirt virtual network to attach the guest to.
.IP "-N HOST, --netfshost HOST"
For the
.B create-pool
name or IP of the NFS server
.IP "-p PATH, --path PATH"
For the
.B create-pool
path of the NETFS resource.

.IP "-p POOL, --pool POOL"
The name of the pool to be used to create virtual disk.
When used, the disk size must be also specified. To get the list of pool available on the host, use
the following command
.B /usr/bin/virsh pool-list.
This option is exclusive with --disk.
.IP "-s DISK_SIZE, --disk-size DISK_SIZE"
The size of the disk in GB  to be created within the given storage pool. This option is mandatory when the --pool option is specified
.IP "-V VIRT-INSTALL_ARGS, --virt VIRT-INSTALL_ARGS"
Each argument that appears after either -V or --virt is passed into virt-install when
this tool executes that command.
.B  oci-kvm
 itself provides the following arguments:
--hvm, --name, --cpu, --disk, --network.
.IP "-v VCN_CIDR, --vcn-cidr VCN_CIDR"
For the
.B create-network
command, the VCN CIDR block used by the vNIC to be used.
.IP "-F IP_FIRST, --ip-first IP_FIRST"
For the
.B create-network
command, specify the first IP address in the virtual network address space.
.IP "-S IP_START, --ip-start IP_START"
For the
.B create-network
command, specify the first IP address in the virtual network address space.
.IP "-E IP_END, --ip-end IP_END"
For the
.B create-network
command, specify the last IP address in the virtual network address space.
.IP "-P IP_PREFIX, --ip-prefix IP_PREFIX"
For the
.B create-network
command, specify the last IP address in the virtual network address space.
.IP --help

.SH EXAMPLES

oci-kvm create-pool --disk /dev/sdb
.RS 3
Creates a storage pool on disk /dev/sdb. Name of the pool will be
.I sdb
.RE

oci-kvm create-pool --netfshost 100.100.231.9 --path /FileSystem-20190405-1454 --name guest_pool
.RS 3
Creates a storage pool on NFS resource FileSystem-20190405-1454 on NFS server 100.100.231.9.
.RE

oci-kvm create --disk-size 128 --pool guest_pool --net 10.0.0.64 -D foo  --virt --cpu 1 --memory 8g --pxe
.RS 3
Creates a guest with a root disk of 128GB on storage pool named foo
.RE

oci-kvm create-network --name=mynet0 --network-name 10.0.1.2 --vcn-cidr=10.0.0.0/16 --ip-first=10.0.2.20 --ip-start=10.0.2.10 --ip-end=10.0.2.30 --ip-prefix=24
.RS 3
Creates virtual network named mynet0 on vNIC with 10.0.1.2 address
.RE

.SH DIAGNOSTICS
Return an exit status of 0 for success or 1 if an error occured.

.SH "SEE ALSO"
.BR ocid (8)
.BR oci-utils.conf.d (5)
