.\" Process this file with
.\" groff -man -Tascii oci-network-config.1
.\"
.\" Copyright (c) 2017, 2022 Oracle and/or its affiliates. All rights reserved.
.\" Licensed under the Universal Permissive License v 1.0 as shown
.\" at http://oss.oracle.com/licenses/upl.
.\"
.TH OCI-NETWORK-CONFIG 1 "MAY 2018" Linux "User Manuals"
.SH NAME
oci-network-config \- configure network devices on Oracle Cloud Infrastructure compute instances
.SH SYNOPSIS

.B oci-network-config
usage

.B oci-network-config
show [-h|--help] [-I ITEM|--include ITEM] [-X ITEM|--exclude ITEM] [--output-mode MODE] [--details]

.B oci-network-config
show-vcns [-h|--help] [--output-mode MODE] [--details] [--ocid VCN_OCID] [--name VCN_NAME] [--no-truncate]

.B oci-network-config
show-subnets [-h|--help] [--output-mode MODE] [--details] [--ocid SUBNET_OCID] [--name SUBNET_NAME] [--no-truncate]

.B oci-network-config
show-vnics [-h|--help] [--output-mode MODE] [--details] [--ocid VNIC_OCID] [--name VNIC_NAME] [--ip-adress PRIMARY_IP] [--no-truncate]

.B oci-network-config
show-vnics-all [-h|--help] [--output-mode MODE]

.B oci-network-config
configure [-h|--help] [-n FORMAT|--namespace FORMAT] [-r |--start-sshd] [-I ITEM|--include ITEM] [-X ITEM|--exclude ITEM]

.B oci-network-config
unconfigure [-h|--help] [-I ITEM|--include ITEM] [-X ITEM|--exclude ITEM]

.B oci-network-config
attach-vnic [-h|--help] [-I IP_ADDR|--ip-addres IP_ADDR] [-i INDEX |--nic-index INDEX] [--subnet SUBNET]
[-n NAME |--name NAME] [--ipv4|-ipv4] [--ipv6|-ipv6] [--assign-public-ip] [--configure]

.B oci-network-config
detach-vnic [-h|--help] [-I IP_ADDR|--ip-addres IP_ADDR] [--ocid OCID]

.B oci-network-config
add-secondary-addr [-h|--help] [--ipv4|-ipv4] [--ipv6|-ipv6] [-I IP_ADDR|--ip-addres IP_ADDR] [--ocid OCID]

.B oci-network-config
remove-secondary-addr [-h|--help] [-I IP_ADDR|--ip-addres IP_ADDR]


.SH INSTALLATION and AUTHORIZATION
.B oci-network-config
requires the services of the python
.B oci-sdk
package.

The
.B oci-utils
package has a dependency on the
.B oci-sdk
package and the correct version of the python
.B oci-sdk
package is installed at
.B oci-utils
install time.

To use the Oracle Cloud Infrastructure services authorization is required. One option is direct authentication via a
config file.  See https://docs.us-phoenix-1.oraclecloud.com/Content/API/Concepts/sdkconfig.htm
for more information.
Another option for authorizing the use of Oracle Cloud Infrastructure services from an instance is
using Instance Principals.  The Oracle Cloud Infrastructure SDK does not need configuration on the
instance when the instance is part of a dynamic group that was granted access
to Oracle Cloud Infrastructure services.
See https://docs.us-phoenix-1.oraclecloud.com/Content/Identity/Tasks/callingservicesfrominstances.htm for further details.

.SH OCID

When the
.BR ocid(8)
service is enabled, it runs the network configuration utility each time the VNIC configuration metadata
of the instance changes.
It also restores the VNIC configuration after rebooting the system.  If
.BR ocid(8)
service is not enabled the
.B oci-network-config configure
 script must be run periodically to pick up changes in VNIC provisioning
(whether adding or deleting). Note that these IP configuration changes are not persistent,
the script must, at a minimum, be run after each startup.

To exclude VNICs, IP addresses or VLAN interfaces from automatic configuration use the -X (or --exclude) option.
Exclusions specified with this option are persistent so that they also apply when
.BR ocid(8)
runs this utility.  The exclusion remains in place until the VNIC/address/interface is re-included
using the -I (or --include) option.

.SH DESCRIPTION

The
.B oci-network-config
utility shows the current
Virtual interface Cards provisioned in the
Oracle Cloud Infrastructure
and configured on this instance. When a secondary VNIC is provisioned in Oracle Cloud Infrastructure it must be
explicitly configured on the instance using
.B oci-network-config
or similar commands.

By default this command displays the currently provisioned VNICs and the current IP configuration for this instance.
VNICs that are not yet configured are marked with
.B ADD
and IP configurations that no longer have an associated VNIC are marked with
.B DELETE.

Using the 
.B configure
sub-command, it configures VNICs that do not have an IP configuration and deletes the IP configurations of
VNICs that are not currently provisioned. This puts the instance IP configuration in sync with current
Oracle Cloud Infrastructure provisioning.

The configuring interfaces can optionally be placed inside separate network namespaces. This is necessary when
VNICs are in subnets (different VCNs) with overlapping address blocks and the network applications are not bound
directly to interfaces. Network namespaces require applications to be launched in them explicitly
(via 'ip netns exec <ns>') in order to establish association with the interface. When namespaces are not used,
policy-based routing is configured to provide a default route to the secondary VNIC\'s virtual router
(default gateway) when the VNIC\'s address is the source address.

Bare Metal secondary VNICs are configured using VLANs (where there is no corresponding physical interface).
These will look like 2 additional interfaces when showing IP links, with names like
.B MACVLAN_FORMAT
for the MAC VLAN and
.B VLAN_FORMAT
for the IP VLAN.

Using the
.B unconfigure
sub-command, it deletes all IP configuration for provisioned secondary VNICs except the ones excluded earlier.

The
.B attach-vnic
and
.B detach-vnic
sub-commands allows creating a new VNIC for the instance, detaching a VNIC from the instance,
or adding/removing private IP addresses to/from an existing VNIC.

The
.B add-secondary-addr
and
.B remove-secondary-addr
sub-commands allows adding/removing private IP addresses to/from an existing VNIC.


.TP
oci-network-config show
Show information on all provisioning and interface configuration. This is the default action if no options are given.

Columns:
    State     'ADD' indicates missing IP config, 'DELETE' missing VNIC, 'EXCL' excluded (-X)
    Link      interface (underlying physical)
    Status    state of interface
    Ip        IP address
    VNIC      VNIC friendly name
    MAC       MAC address
    Hostname  the configured hostname of that vNIC
    Subnet    subnet CIDR and name
    Router IP virutal router IP address
    Namespace namespace (if any)
    Index     interface index
    VLAN tag  VLAN tag
    VLAN      IP virtual LAN 
.RS
.IP "-h, --help"
Print a summary of the command line options.
.IP "-X ITEM, --exclude ITEM"
Persistently exclude
.B ITEM
from automatic configuration/deconfiguration. Use the --include option to include the
.B ITEM
again.
.B ITEM
can be a VNIC OCID, an IP address or a VLAN interface name.
.IP "-I ITEM, --include ITEM"
Include an
.B ITEM
that was previously excluded using the --exclude option in automatic configuration/deconfiguration.
.IP "--details"
Display detailed information.
.IP --output-mode={parsable,table,json,text}
Display list of block volumes as table, using json format, simple text or using parsable output
(default is table).
.RE
.TP
oci-network-config show-vcns
Shows vcn information

Columns:
    Name
    OCID
    ipv4 cidr block
    ivp6 cidr block
    ipv4 cidr blocks
    DNS label
    State
    Lifecycle state
.RS
.IP "-h, --help"
Print a summary of the command line options.
.IP "--ocid VCN_NAME"
Show only information of subnet matching name.
.IP "--ocid VCN_OCID"
Show  information of subnet matching ocid.
.IP "--details"
Display detailed information.
.IP --output-mode={parsable,table,json,text}
Display list of block volumes as table, using json format, simple text or using parsable output
(default is table).
.IP --no-truncate
Do not truncate long values during output.
.RE
.TP
oci-network-config show-subnets
Shows subnet information

Columns:
    Name
    OCID
    ipv4 cidr block
    ivp6 cidr block
    VNC Name
    VCN OCID
    Public
    Public ingress
    DNS label
    Domain name
    Lifecycle state
.RS
.IP "-h, --help"
Print a summary of the command line options.
.IP "--ocid SUBNET_NAME"
Show only information of subnet matching name.
.IP "--ocid SUBNET_OCID"
Show  information of subnet matching ocid.
.IP "--details"
Display detailed information.
.IP --output-mode={parsable,table,json,text}
Display list of block volumes as table, using json format, simple text or using parsable output
(default is table).
.IP --no-truncate
Do not truncate long values during output.
.RE
.TP
oci-network-config show-vnics
Shows VNICs information of this instance

Columns:
    Name
    Private IP
    MAC address
    Configuration state
    OCID
    Primary IP
    Subnet name
    Subnet OCID
    Subnet (ipv4) cidr block
    Availability State
    Nic index
    Public IP

For secondary addresses:
    Private IP (ipv4 and ipv6)
    OCID
.RS
.IP "-h, --help"
Print a summary of the command line options.
.IP "--ocid VNIC_NAME"
Show only information of vNIC matching name.
.IP "--ocid VNIC_OCID"
Show  information of vNIC matching ocid.
.IP "--ip-address PRIMARY_IP"
Show information of vNIC matching IP as primary IP.
.IP "--details"
Display detailed information.
.IP --output-mode={parsable,table,json,text}
Display list of block volumes as table, using json format, simple text or using parsable output
(default is table).
.IP --no-truncate
Do not truncate long values during output.
.RE
.TP
oci-network-config show-vnics-all
Shows information on all VNICs of the instance, detailed and not truncated. This is a shortcut for show-vnics --details --no-truncate.
.RE
.TP
oci-network-config configure
Puts in sync network configuration. Add IP configuration for VNICs that are not configured and delete VNICs
that are no longer provisioned.
.RS
.IP "-h, --help"
Print a summary of the command line options.
.IP "-X ITEM, --exclude ITEM"
Persistently exclude
.B ITEM
from automatic configuration/deconfiguration. Use the --include option to include the
.B ITEM
again.
.B ITEM
can be a VNIC OCID, an IP address or a VLAN interface name.
.IP "-I ITEM, --include ITEM"
Include an
.B ITEM
that was previously excluded using the --exclude option in automatic configuration/deconfiguration.
.IP "-n FORMAT, --namespace FORMAT"
When configuring, place interfaces in namespace identified by the given format. Format can
include
.B nic
and
.B vltag
variables. The name defaults to
.B DEF_NS_FORMAT_BM
for
.B BMs
and
.B DEF_NS_FORMAT_VM
for
.B VMs
.
When configuring multiple VNICs ensure the namespaces are unique.
.IP "-r, --sshd"
Start sshd in namespace (if -n or --namespace is present)
.RE
.TP
oci-network-config unconfigure
Deconfigure all VNICs (except the primary).
.RS
.IP "-h, --help"
Print a summary of the command line options.
.IP "-X ITEM, --exclude ITEM"
Persistently exclude
.B ITEM
from automatic configuration/deconfiguration. Use the --include option to include the
.B ITEM
again.
.B ITEM
can be a VNIC OCID, an IP address or a VLAN interface name.
.IP "-I ITEM, --include ITEM"
Include an
.B ITEM
that was previously excluded using the --exclude option in automatic configuration/deconfiguration.
.RE
.TP
oci-network-config attach-vnic
Create a new VNIC and attach it to this instance.  Use the --subnet option to
choose a subnet and --private-ip to choose a specific private IP address.
.RS
.IP "-h, --help"
Print a summary of the command line options.
.IP "-I|--ip-address ADDR"
Assign the given private IP address. Without this option an unused IP address from the subnet will be
assigned automatically.
.IP "-ipv4|--ipv4"
IF the option
.B --ip-address ADDR
is missing, an unused
.B ipv4
address from the subnet is selected. If this option is present, options
.B --ipv4
and
.B --ipv6
are ignored.
.IP "-ipv6|--ipv6"
IF the option
.B --ip-address ADDR
is missing, an unused
.B ipv6
address from the subnet is selected. This option is not yet supported by OCI.
The options
.B --ipv4
and
.B --ipv6
are mutually exclusive.
.IP "-i|--nic-index IND"
Physical NIC index. Assign the VNIC to this physical network interface card.
Default value is 0. (only relevent on BareMetal shapes)
.IP "--subnet SUBNET"
Connect the VNIC to the given
.B SUBNET.
The
.B SUBNET
can be an OCID or a regular expression that is matched against the display name
of all available subnets.  When --ip-address is used, the subnet is inferred
from the IP address, or it defaults to the subnet of the primary VNIC.
.IP "-n|--name NAME"
When creating a new VNIC, set the display name and hostname of the VNIC to NAME.
.IP "--assign-public-ip"
Assign a public IP address to the new VNIC.  By default only a private IP address is assigned.
.RE
.TP
oci-network-config detach-vnic
Detach and delete the VNIC with the given OCID or IP address.  The primary
VNIC cannot be detached.  Any secondary private IP addresses attached to the
VNIC are also deleted.
.RS
.IP "-h, --help"
Print a summary of the command line options.
.IP "-I|--ip-address ADDR"
Detach the vNIC with the given ip address configured on it.
.IP "--ocid OCID"
Detach the vNIC with the given OCID
.RE
.TP
oci-network-config add-secondary-addr
Add a secondary private IP address to an existing VNIC.
.RS
.IP "-h, --help"
Print a summary of the command line options.
.IP "-I|--ip-address ADDR"
Secondary private IP to to be added. If this options is used, the type is derived from the ip address string.
If this option is absent, a free ipv4 address is selected if the --ipv6 flag is not set, in which case a free ipv6
address is added. If this option is present, options
.B --ipv4
and
.B --ipv6
are ignored.
.IP "--ocid OCID"
Assign the secondary address to the vNIC of the given OCID.
.IP "--ipv4|-ipv4"
The secondary address to be added is a free
.B ipv4
address selected from the subnet. This is the default.
.IP "--ipv6|-ipv6"
The secondary address to be added is a free
.B ipv6
address from the subnet. The options
.B --ipv4
and
.B --ipv6
are mutually exclusive.
.RE
.TP
oci-network-config remove-secondary-addr
Remove the secondary private IP address from an existing VNIC.
.RS
.IP "-h, --help"
Print a summary of the command line options.
.IP "-I|--ip-address ADDR"
Secondary private IP to to be removed.


.SH EXAMPLES
.PP
.nf
.RS
sudo oci-network-config add-secondary-addr --ip-address 10.0.1.200
.RE
.fi
.PP
Attaches and configures a new secondary private IPv4 address, 10.0.1.200 on the
primary VNIC.  See
.BR oci-utils.conf.d(5)
for information about configuring oci-utils to work as the root user.
.PP
.nf
.RS
sudo oci-network-config add-secondary-addr --ipv6 --ocid ocid1.vnic.oc1.uk-london-1.some_uuid
.RE
.fi
.PP
Attaches and configures a new secondary private IPv6 address on the VNIC with the specified ocid. As the address is
not specified, a free address from the subnet is selected.
.PP
.nf
.RS
sudo oci-network-config remove-secondary-addr 10.0.1.200
.RE
.fi
.PP
Delete and de-configure the secondary private IP set up in the previous example.
.PP
.nf
.RS
sudo oci-network-config attach-vnic --assign-public-ip --subnet my-subnet
.RE
.fi
.PP
Create a new VNIC in the
.B my-subnet
subnet.  An unused IP address from
.B my-subnet
is assigned automatically.  A public IP address is also assigned to the VNIC.

.SH DIAGNOSTICS
Return an exit status of 0 for success or 1 if an error occured.
.SH "SEE ALSO"
.BR ocid (8)
.BR oci-utils.conf.d (5)
.BR sudo (8)
