#!/bin/bash
# Copyright (c) 2020, 2021 Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown
# at http://oss.oracle.com/licenses/upl.

export search ${dns_search_domains}
export nameserver ${dns_server_ip}